### ISSUE TITLE
Support for XBOX One DIGITAL TV Tuner

### ISSUE THREAD

**Issue by mky** [hselasky/webcamd#1]
Since Linux 4.16 there is a new DVB driver for XBOX One DIGITAL TV Tuner. I tried to launch this tuner with new webcamd 4.17 but only with partial success. This tuner needs two firmwares:
- dvb-usb-dib0700-1.20.fw for DiBcom DiB0700 USB bridge
- dvb-demod-mn88472-02.fw for Panasonic MN88472 DVB-T/DVB-T2/DVB-C demodulator

The only first is loaded by webcamd. Currently the XBOX ONE DIGITAL TV Tuner looks on FreeBSD as follow:

`# usbconfig -d 0.5`
`ugen0.5: <Microsoft Corp. Xbox USB Tuner> at usbus0, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (500mA)`

`# webcamd -d 0.5`
`Attached to ugen0.5[0]`
`Loading firmware at '/boot/modules/dvb-usb-dib0700-1.20.fw', f=7`
`Creating /dev/dvb/adapter0/demux0`
`Creating /dev/dvb/adapter0/dvr0`

Is it possible to fix this to load the second firmware for DVB demodulator?
I am using FreeBSD 11.1-RELEASE-p10 (amd64).

**Comment by hselasky** [comment]
Hi,

You might want to check the configuration knobs if all entries needed are set to "yes":

config_dvb.in:CONFIG_DVB_MN88472=y
config_dvb.in:CONFIG_DVB_USB_DIB0700=y

--HPS

**Comment by hselasky** [comment]
You can also try to compile the driver with debugging support and see if there are any failures.

**Comment by mky** [comment]
I have already enable both knobs. After "make patch" on the webcamd port I got:

```
# grep -E "DIB0700|MN88472" config_dvb.in
CONFIG_DVB_MN88472=y
CONFIG_DVB_USB_DIB0700=y
```

I recompiled webcamd with debbuging support. Here is the output:
```
# webcamd -d 0.5
Linux video capture interface: v2.00
IR NEC protocol handler initialized
IR RC5(x/sz) protocol handler initialized
IR RC6 protocol handler initialized
IR JVC protocol handler initialized
IR Sony protocol handler initialized
IR SANYO protocol handler initialized
IR XMP protocol handler initialized
b2c2-flexcop: B2C2 FlexcopII/II(b)/III digital TV receiver chip loaded successfully
USB Video Class driver (1.1.1)
cpia2: V4L-Driver for Vision CPiA2 based cameras v3.0.1
pvrusb2: V4L in-tree version:Hauppauge WinTV-PVR-USB2 MPEG2 Encoder/Tuner
pvrusb2: Debug mask is 31 (0x1f)
USBVision USB Video Device Driver for Linux : 0.9.11
Attached to ugen0.5[0]
dvb-usb: found a 'Microsoft Xbox One Digital TV Tuner' in cold state, will try to load a firmware
Loading firmware at '/boot/modules/dvb-usb-dib0700-1.20.fw', f=7
dvb-usb: downloading firmware from file 'dvb-usb-dib0700-1.20.fw'
dib0700: firmware started successfully.
dvb-usb: found a 'Microsoft Xbox One Digital TV Tuner' in warm state.
dvb-usb: will pass the complete MPEG2 transport stream to the software demuxer.
DBG: 128-0018: 

DBG: 128-0018: chip id=02

INFO: 128-0018: Panasonic MN88472 successfully identified

DBG: 128-0018: 

DBG: 128-0018: 

dvb-usb: no frontend was attached by 'Microsoft Xbox One Digital TV Tuner'
dvb-usb: Microsoft Xbox One Digital TV Tuner successfully initialized and connected.
Creating /dev/dvb/adapter0/demux0
Creating /dev/dvb/adapter0/dvr0
```

**Comment by hselasky** [comment]
dvb-usb: no frontend was attached by 'Microsoft Xbox One Digital TV Tuner'

Is it possible to get the enumeration output from a Linux box with recent Linux kernel for your device?

It looks like some chipdriver is missing from config_dvb.in  .   build/config.h tells all that are "=n" after "make configure"

--HPS

**Comment by mky** [comment]
I switched to the Linux Debian 9.0 with kernel 4.16 from backports and checked dmesg output. Here is some more interesting information:

```
[    9.696105] usb 1-3: new high-speed USB device number 2 using ehci-pci
[    9.854142] usb 1-3: New USB device found, idVendor=045e, idProduct=02d5
[    9.854153] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    9.854158] usb 1-3: Product: Xbox USB Tuner
[    9.854162] usb 1-3: Manufacturer: Microsoft Corp.
[    9.854166] usb 1-3: SerialNumber: 001392140415
[..]
[   13.039989] dvb-usb: found a 'Microsoft Xbox One Digital TV Tuner' in warm state.
[   13.040866] dvb-usb: will pass the complete MPEG2 transport stream to the software demuxer.
[   13.042632] dvbdev: DVB: registering new adapter (Microsoft Xbox One Digital TV Tuner)
[..]
[   13.295537] mn88472 2-0018: Panasonic MN88472 successfully identified
[   13.338902] tda18250 2-0060: NXP TDA18250BHN/M successfully identified
[   13.342396] usb 1-3: DVB: registering adapter 1 frontend 0 (Panasonic MN88472)...
[   13.342650] dvb-usb: Microsoft Xbox One Digital TV Tuner successfully initialized and connected.
[   13.342964] usbcore: registered new interface driver dvb_usb_dib0700
```

I think that the most interested is that the Linux detects NXP TDA18250BHN/M tuner, which is not detected by webcamd. I checked the port of webcamd and after "make patch" the build/config.h has disabled support for this tuner:
```
# grep TDA18250 build/config.h 
#undef	CONFIG_MEDIA_TUNER_TDA18250 /* n */
```
I changed it manually to:
`#define  	CONFIG_MEDIA_TUNER_TDA18250 /* n */`

And I compiled webcamd again but it does not help. The tuner was not detected. Probably something I'm doing wrong. How to properly enable driver for TDA18250?

**Comment by hselasky** [comment]
Can you try this patch instead, right after "make extract patch" before "make all"

```
===================================================================
--- config_dvb.in	(revision 4155)
+++ config_dvb.in	(working copy)
@@ -189,6 +189,7 @@
 CONFIG_MEDIA_TUNER_SI2157=y
 CONFIG_MEDIA_TUNER_TDA18212=y
 CONFIG_MEDIA_TUNER_TDA18218=y
+CONFIG_MEDIA_TUNER_TDA18250=y
 CONFIG_MEDIA_TUNER_TDA18271=y
 CONFIG_MEDIA_TUNER_TDA827X=y
 CONFIG_MEDIA_TUNER_TDA8290=y
```

**Comment by mky** [comment]
I've patched config_dvb.in as you wrote and now it works! 

`# webcamd -d 0.3`
```
Linux video capture interface: v2.00
IR NEC protocol handler initialized
IR RC5(x/sz) protocol handler initialized
IR RC6 protocol handler initialized
IR JVC protocol handler initialized
IR Sony protocol handler initialized
IR SANYO protocol handler initialized
IR XMP protocol handler initialized
b2c2-flexcop: B2C2 FlexcopII/II(b)/III digital TV receiver chip loaded successfully
USB Video Class driver (1.1.1)
cpia2: V4L-Driver for Vision CPiA2 based cameras v3.0.1
pvrusb2: V4L in-tree version:Hauppauge WinTV-PVR-USB2 MPEG2 Encoder/Tuner
pvrusb2: Debug mask is 31 (0x1f)
USBVision USB Video Device Driver for Linux : 0.9.11
Attached to ugen0.3[0]
dvb-usb: found a 'Microsoft Xbox One Digital TV Tuner' in warm state.
dvb-usb: will pass the complete MPEG2 transport stream to the software demuxer.
DBG: 128-0018: 

DBG: 128-0018: chip id=02

INFO: 128-0018: Panasonic MN88472 successfully identified

DBG: 128-0018: 

DBG: 128-0060: chip_id=c7:4a:21
INFO: 128-0060: NXP TDA18250BHN/M successfully identified
DBG: 128-0060: power state: 0
DBG: : dvb_register_frontend:

INFO: : DVB: registering adapter 0 frontend 0 (Panasonic MN88472)...

DBG: : dvb_frontend_clear_cache: Clearing cache for delivery system 3

dvb-usb: Microsoft Xbox One Digital TV Tuner successfully initialized and connected.
Creating /dev/dvb/adapter0/demux0
Creating /dev/dvb/adapter0/dvr0
DBG: : dvb_frontend_open:

DBG: : dvb_frontend_release:

Creating /dev/dvb/adapter0/frontend0
```

I've tested this tuner with tvheadend and I can confirm that it works properly for DVB-C network. I have no possibility to test it with DVB-T but I think that it should work too. Please add the option "CONFIG_MEDIA_TUNER_TDA18250=y" to config_dvb.in permamently.

Thank you for help!

**Comment by hselasky** [comment]
https://github.com/hselasky/webcamd/commit/a7fd5b6377b3a22e652e9ddc0574b8b745e8fb68
