### ISSUE TITLE
Porting drivers for OSX

### ISSUE THREAD

**Issue by j1m1l0k0** [hselasky/webcamd#4]
Hello, how are you ?
Can you tell if there is a lot of difference between the freebsd and osx structures in the case of porting the drivers? Do you have any information on the subject? Thank you.

**Comment by hselasky** [comment]
Hi,
You'll need to implement proper libcuse and libusb support for OS-X and then it will work out of the box.
--HPS

**Comment by j1m1l0k0** [comment]
@hselasky thanks man !

**Comment by hselasky** [comment]
Are there any patches? Can this issue be closed?

--HPS

**Comment by hselasky** [comment]
Closing for now.
