### ISSUE TITLE
Incorporate v4l2loopback / loopback devices?

### ISSUE THREAD

**Issue by davidschlachter** [hselasky/webcamd#7]
On Linux, I can create a virtual webcam device with [`v4l2loopback`](https://github.com/umlaeute/v4l2loopback/). Then, I can pipe a video file (in [an appropriate format](https://github.com/umlaeute/v4l2loopback/wiki/FFmpeg)) to the virtual device. Programs that would normally use a webcam will then be able to use the device as a video source. For example, `v4l2loopback` is used by software such as [OBS Studio](https://obsproject.com/) (add effects, color adjustment, text, etc) or [DroidCam](https://github.com/dev47apps/droidcam/) (use phone as video source) to provide a virtual webcam that can be used for videoconferencing.

Does `webcamd` have any current loopback abilities? Would it be possible to include `v4l2loopback` as a (virtual) driver within `webcamd`, or to port it as a separate package that would run within the FreeBSD userspace through `webcamd`?

**Comment by hselasky** [comment]
Yes, I think it should work with a little love.

Just submodule the loopback repo inside webcamd, then update the main Makefile to build the files needed.

Further, webcamd only supports module_param's. I think sysfs is not supported, so you need to implement another way to setup this loopback, for example reading sysfs's from module_param's when webcamd starts.

--HPS

**Comment by davidschlachter** [comment]
Thanks for the reply. I'll take a look at this when I get the chance. Once I have the build system figured out and get `v4l2-loopback` to build, I'll take look at setting up the loopback device when starting `webcamd`, maybe with an extra command line argument.

**Comment by hselasky** [comment]
Cool :+1:

**Comment by rajhlinux** [comment]
I am also interested in using loopback on FreeBSD, is there a tutorial on how to do this?

Thanks.

**Comment by davidschlachter** [comment]
Take a look at the [man page](https://www.freebsd.org/cgi/man.cgi?query=webcamd&sektion=8&manpath=freebsd-release-ports) (`-c` option). Personally, I used this feature to use the [virtual camera in OBS Studio](https://www.davidschlachter.com/misc/freebsd-obs-virtualcam).

**Comment by hselasky** [comment]
`webcamd -c v4l2loopback`

**Comment by hselasky** [comment]
Maybe we could add an example to the manual page of webcamd? Feel free to submit a patch!

**Comment by rajhlinux** [comment]
Thanks for the reply.

I have two HDMI to USB3.0 captures cards working on FreeBSD 13.1

After entering:
`webcamd -c v4l2loopback`

The command line just freezes after showing the below command, not sure if it's safe to close the terminal:
`webcamd 1618 - - Creating /dev/video4
`

![Screenshot_20220901_032219](https://user-images.githubusercontent.com/61344181/187856248-dc1a2546-61a1-49b8-adc9-0dc0b1c9a2fb.png)

Everything seems to be working after the below command: 
`ffmpeg -re -i /dev/video0 -map 0:v -vf format=yuv420p -f v4l2 /dev/video4`

Thanks.

**Comment by hselasky** [comment]
> The command line just freezes after showing the below command, not sure if it's safe to close the terminal:
> `webcamd 1618 - - Creating /dev/video4 `

Add "-B" option to run in background!
